# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FewShotSegmenterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_classes = channel.unary_unary(
                '/Ivitec.FewShotSegmenterService/get_classes',
                request_serializer=service__pb2.Void.SerializeToString,
                response_deserializer=service__pb2.StringListResponse.FromString,
                _registered_method=True)
        self.get_nshot = channel.unary_unary(
                '/Ivitec.FewShotSegmenterService/get_nshot',
                request_serializer=service__pb2.Void.SerializeToString,
                response_deserializer=service__pb2.IntResponse.FromString,
                _registered_method=True)
        self.segment = channel.unary_unary(
                '/Ivitec.FewShotSegmenterService/segment',
                request_serializer=service__pb2.Image.SerializeToString,
                response_deserializer=service__pb2.SegmentMapResponse.FromString,
                _registered_method=True)


class FewShotSegmenterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_classes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_nshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def segment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FewShotSegmenterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_classes': grpc.unary_unary_rpc_method_handler(
                    servicer.get_classes,
                    request_deserializer=service__pb2.Void.FromString,
                    response_serializer=service__pb2.StringListResponse.SerializeToString,
            ),
            'get_nshot': grpc.unary_unary_rpc_method_handler(
                    servicer.get_nshot,
                    request_deserializer=service__pb2.Void.FromString,
                    response_serializer=service__pb2.IntResponse.SerializeToString,
            ),
            'segment': grpc.unary_unary_rpc_method_handler(
                    servicer.segment,
                    request_deserializer=service__pb2.Image.FromString,
                    response_serializer=service__pb2.SegmentMapResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Ivitec.FewShotSegmenterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Ivitec.FewShotSegmenterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FewShotSegmenterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_classes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Ivitec.FewShotSegmenterService/get_classes',
            service__pb2.Void.SerializeToString,
            service__pb2.StringListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_nshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Ivitec.FewShotSegmenterService/get_nshot',
            service__pb2.Void.SerializeToString,
            service__pb2.IntResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def segment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Ivitec.FewShotSegmenterService/segment',
            service__pb2.Image.SerializeToString,
            service__pb2.SegmentMapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
